spring:
  data:
    mongodb:
      username: mongo
      password: mongo
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerialization
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.zangar.ecommerce.kafka.OrderConfirmation
  application:
    name: notification
