spring:
  config:
    import: optional:configserver:http://localhost:8888 # ????? ???????? ?????????? ???????????? ?? config-server ?? ?????? http://localhost:8888
    # optional ???????? ??? ?????????? ??? ????? ??????????? ???? ???? config server ?? ????????
  application:
    name: discovery-service
